# The font family to use
font-family = "Fira Code"

# Hide mouse immediately when typing.
mouse-hide-while-typing = true

# The style of the cursor
cursor-style = underline

# Whether to automatically copy selected text to the clipboard.
copy-on-select = clipboard

# The opacity level of the background
background-opacity = 0.8

# Horizontal window padding.
window-padding-x = 30

# Vertical window padding.
window-padding-y = 30

# The viewport dimensions are usually not perfectly divisible by the cell size.
window-padding-balance = true

theme = 0x96f
